# coding: utf-8

"""
    Mux API

    Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: devex@mux.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import mux_python
from mux_python.models.monitoring_breakdown_timeseries_values import MonitoringBreakdownTimeseriesValues  # noqa: E501
from mux_python.rest import ApiException

class TestMonitoringBreakdownTimeseriesValues(unittest.TestCase):
    """MonitoringBreakdownTimeseriesValues unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MonitoringBreakdownTimeseriesValues
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = mux_python.models.monitoring_breakdown_timeseries_values.MonitoringBreakdownTimeseriesValues()  # noqa: E501
        if include_optional :
            return MonitoringBreakdownTimeseriesValues(
                values = [
                    mux_python.models.monitoring_breakdown_timeseries_datapoint.MonitoringBreakdownTimeseriesDatapoint(
                        value = '', 
                        metric_value = 1.337, 
                        concurrent_viewers = 56, )
                    ], 
                date = ''
            )
        else :
            return MonitoringBreakdownTimeseriesValues(
        )

    def testMonitoringBreakdownTimeseriesValues(self):
        """Test MonitoringBreakdownTimeseriesValues"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
