# coding: utf-8

"""
    Mux API

    Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: devex@mux.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import mux_python
from mux_python.api.transcription_vocabularies_api import TranscriptionVocabulariesApi  # noqa: E501
from mux_python.rest import ApiException


class TestTranscriptionVocabulariesApi(unittest.TestCase):
    """TranscriptionVocabulariesApi unit test stubs"""

    def setUp(self):
        self.api = mux_python.api.transcription_vocabularies_api.TranscriptionVocabulariesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_transcription_vocabulary(self):
        """Test case for create_transcription_vocabulary

        Create a Transcription Vocabulary  # noqa: E501
        """
        pass

    def test_delete_transcription_vocabulary(self):
        """Test case for delete_transcription_vocabulary

        Delete a Transcription Vocabulary  # noqa: E501
        """
        pass

    def test_get_transcription_vocabulary(self):
        """Test case for get_transcription_vocabulary

        Retrieve a Transcription Vocabulary  # noqa: E501
        """
        pass

    def test_list_transcription_vocabularies(self):
        """Test case for list_transcription_vocabularies

        List Transcription Vocabularies  # noqa: E501
        """
        pass

    def test_update_transcription_vocabulary(self):
        """Test case for update_transcription_vocabulary

        Update a Transcription Vocabulary  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
