# coding: utf-8

"""
    Mux API

    Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: devex@mux.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import mux_python
from mux_python.api.web_inputs_api import WebInputsApi  # noqa: E501
from mux_python.rest import ApiException


class TestWebInputsApi(unittest.TestCase):
    """WebInputsApi unit test stubs"""

    def setUp(self):
        self.api = mux_python.api.web_inputs_api.WebInputsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_web_input(self):
        """Test case for create_web_input

        Create a new Web Input  # noqa: E501
        """
        pass

    def test_delete_web_input(self):
        """Test case for delete_web_input

        Delete a Web Input  # noqa: E501
        """
        pass

    def test_get_web_input(self):
        """Test case for get_web_input

        Retrieve a Web Input  # noqa: E501
        """
        pass

    def test_launch_web_input(self):
        """Test case for launch_web_input

        Launch a Web Input  # noqa: E501
        """
        pass

    def test_list_web_inputs(self):
        """Test case for list_web_inputs

        List Web Inputs  # noqa: E501
        """
        pass

    def test_reload_web_input(self):
        """Test case for reload_web_input

        Reload a Web Input  # noqa: E501
        """
        pass

    def test_shutdown_web_input(self):
        """Test case for shutdown_web_input

        Shut down a Web Input  # noqa: E501
        """
        pass

    def test_update_web_input_url(self):
        """Test case for update_web_input_url

        Update Web Input URL  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
