# coding: utf-8

"""
    Mux API

    Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: devex@mux.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from mux_python.configuration import Configuration


class MonitoringBreakdownTimeseriesValues(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'values': 'list[MonitoringBreakdownTimeseriesDatapoint]',
        'date': 'str'
    }

    attribute_map = {
        'values': 'values',
        'date': 'date'
    }

    def __init__(self, values=None, date=None, local_vars_configuration=None):  # noqa: E501
        """MonitoringBreakdownTimeseriesValues - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._values = None
        self._date = None
        self.discriminator = None

        if values is not None:
            self.values = values
        if date is not None:
            self.date = date

    @property
    def values(self):
        """Gets the values of this MonitoringBreakdownTimeseriesValues.  # noqa: E501


        :return: The values of this MonitoringBreakdownTimeseriesValues.  # noqa: E501
        :rtype: list[MonitoringBreakdownTimeseriesDatapoint]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this MonitoringBreakdownTimeseriesValues.


        :param values: The values of this MonitoringBreakdownTimeseriesValues.  # noqa: E501
        :type values: list[MonitoringBreakdownTimeseriesDatapoint]
        """

        self._values = values

    @property
    def date(self):
        """Gets the date of this MonitoringBreakdownTimeseriesValues.  # noqa: E501


        :return: The date of this MonitoringBreakdownTimeseriesValues.  # noqa: E501
        :rtype: str
        """
        return self._date

    @date.setter
    def date(self, date):
        """Sets the date of this MonitoringBreakdownTimeseriesValues.


        :param date: The date of this MonitoringBreakdownTimeseriesValues.  # noqa: E501
        :type date: str
        """

        self._date = date

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MonitoringBreakdownTimeseriesValues):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MonitoringBreakdownTimeseriesValues):
            return True

        return self.to_dict() != other.to_dict()
