name: Integration Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.11.x'
      - name: Install Python Dependencies
        run: python setup.py install
      - name: Run Integration Tests
        env:
          MUX_TOKEN_ID: ${{ secrets.MUX_TOKEN_ID }}
          MUX_TOKEN_SECRET: ${{ secrets.MUX_TOKEN_SECRET }}
        run: bash test.sh
